export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const UPDATE_PHRASES = 'UPDATE_PHRASES';
export const UPDATE_COUNT = 'UPDATE_COUNT';
export const UPDATE_LENGTH = 'UPDATE_LENGTH';
export const UPDATE_SELECTED_PHRASE = 'UPDATE_SELECTED_PHRASE';
export const UPDATE_WORDLIST = 'UPDATE_WORDLIST';
export const UPDATE_SELECTED_WORDLIST = 'UPDATE_SELECTED_WORDLIST';
